set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P20} [get_ports fpga_rst]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y18} [get_ports fpga_clk]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y9} [get_ports {switch[23]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W9} [get_ports {switch[22]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y7} [get_ports {switch[21]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y8} [get_ports {switch[20]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB8} [get_ports {switch[19]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AA8} [get_ports {switch[18]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V8} [get_ports {switch[17]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V9} [get_ports {switch[16]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB6} [get_ports {switch[15]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB7} [get_ports {switch[14]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V7} [get_ports {switch[13]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AA6} [get_ports {switch[12]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y6} [get_ports {switch[11]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T6} [get_ports {switch[10]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R6} [get_ports {switch[9]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V5} [get_ports {switch[8]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U6} [get_ports {switch[7]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W5} [get_ports {switch[6]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W6} [get_ports {switch[5]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U5} [get_ports {switch[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T5} [get_ports {switch[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T4} [get_ports {switch[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R4} [get_ports {switch[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W4} [get_ports {switch[0]}]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P2} [get_ports {button[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P4} [get_ports {button[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P5} [get_ports {button[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P1} [get_ports {button[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R1} [get_ports {button[0]}]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN A18} [get_ports {dig_en[7]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN A20} [get_ports {dig_en[6]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN B20} [get_ports {dig_en[5]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E18} [get_ports {dig_en[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F18} [get_ports {dig_en[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D19} [get_ports {dig_en[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E19} [get_ports {dig_en[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN C19} [get_ports {dig_en[0]}]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F15} [get_ports DN_A]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F13} [get_ports DN_B]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F14} [get_ports DN_C]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F16} [get_ports DN_D]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E17} [get_ports DN_E]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN C14} [get_ports DN_F]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN C15} [get_ports DN_G]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E13} [get_ports DN_DP]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K17} [get_ports {led[23]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L13} [get_ports {led[22]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M13} [get_ports {led[21]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K14} [get_ports {led[20]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K13} [get_ports {led[19]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M20} [get_ports {led[18]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N20} [get_ports {led[17]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N19} [get_ports {led[16]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M17} [get_ports {led[15]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M16} [get_ports {led[14]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M15} [get_ports {led[13]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K16} [get_ports {led[12]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L16} [get_ports {led[11]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L15} [get_ports {led[10]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L14} [get_ports {led[9]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J17} [get_ports {led[8]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F21} [get_ports {led[7]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G22} [get_ports {led[6]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G21} [get_ports {led[5]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D21} [get_ports {led[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E21} [get_ports {led[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D22} [get_ports {led[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E22} [get_ports {led[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN A21} [get_ports {led[0]}]

connect_debug_port u_ila_1/probe5 [get_nets [list DN_DP_OBUF]]

connect_debug_port u_ila_0/clk [get_nets [list Core_cpu/u_ALU/n_0_514_BUFG]]
connect_debug_port u_ila_0/probe0 [get_nets [list {Core_cpu/Bus_rdata[0]} {Core_cpu/Bus_rdata[1]} {Core_cpu/Bus_rdata[2]} {Core_cpu/Bus_rdata[3]} {Core_cpu/Bus_rdata[4]} {Core_cpu/Bus_rdata[5]} {Core_cpu/Bus_rdata[6]} {Core_cpu/Bus_rdata[7]} {Core_cpu/Bus_rdata[8]} {Core_cpu/Bus_rdata[9]} {Core_cpu/Bus_rdata[10]} {Core_cpu/Bus_rdata[11]} {Core_cpu/Bus_rdata[12]} {Core_cpu/Bus_rdata[13]} {Core_cpu/Bus_rdata[14]} {Core_cpu/Bus_rdata[15]} {Core_cpu/Bus_rdata[16]} {Core_cpu/Bus_rdata[17]} {Core_cpu/Bus_rdata[18]} {Core_cpu/Bus_rdata[19]} {Core_cpu/Bus_rdata[20]} {Core_cpu/Bus_rdata[21]} {Core_cpu/Bus_rdata[22]} {Core_cpu/Bus_rdata[23]} {Core_cpu/Bus_rdata[24]} {Core_cpu/Bus_rdata[25]} {Core_cpu/Bus_rdata[26]} {Core_cpu/Bus_rdata[27]} {Core_cpu/Bus_rdata[28]} {Core_cpu/Bus_rdata[29]} {Core_cpu/Bus_rdata[30]} {Core_cpu/Bus_rdata[31]}]]
connect_debug_port u_ila_1/probe0 [get_nets [list {Core_cpu/Bus_wdata[0]} {Core_cpu/Bus_wdata[1]} {Core_cpu/Bus_wdata[2]} {Core_cpu/Bus_wdata[3]} {Core_cpu/Bus_wdata[4]} {Core_cpu/Bus_wdata[5]} {Core_cpu/Bus_wdata[6]} {Core_cpu/Bus_wdata[7]} {Core_cpu/Bus_wdata[8]} {Core_cpu/Bus_wdata[9]} {Core_cpu/Bus_wdata[10]} {Core_cpu/Bus_wdata[11]} {Core_cpu/Bus_wdata[12]} {Core_cpu/Bus_wdata[13]} {Core_cpu/Bus_wdata[14]} {Core_cpu/Bus_wdata[15]} {Core_cpu/Bus_wdata[16]} {Core_cpu/Bus_wdata[17]} {Core_cpu/Bus_wdata[18]} {Core_cpu/Bus_wdata[19]} {Core_cpu/Bus_wdata[20]} {Core_cpu/Bus_wdata[21]} {Core_cpu/Bus_wdata[22]} {Core_cpu/Bus_wdata[23]} {Core_cpu/Bus_wdata[24]} {Core_cpu/Bus_wdata[25]} {Core_cpu/Bus_wdata[26]} {Core_cpu/Bus_wdata[27]} {Core_cpu/Bus_wdata[28]} {Core_cpu/Bus_wdata[29]} {Core_cpu/Bus_wdata[30]} {Core_cpu/Bus_wdata[31]}]]
connect_debug_port u_ila_1/probe2 [get_nets [list Core_cpu/Bus_wen]]

connect_debug_port u_ila_0/probe0 [get_nets [list {Core_cpu/Bus_addr[28]}]]





create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list cpu_clk_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {dig_en_OBUF[0]} {dig_en_OBUF[1]} {dig_en_OBUF[2]} {dig_en_OBUF[3]} {dig_en_OBUF[4]} {dig_en_OBUF[5]} {dig_en_OBUF[6]} {dig_en_OBUF[7]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list Clkgen/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 24 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {led_OBUF[0]} {led_OBUF[1]} {led_OBUF[2]} {led_OBUF[3]} {led_OBUF[4]} {led_OBUF[5]} {led_OBUF[6]} {led_OBUF[7]} {led_OBUF[8]} {led_OBUF[9]} {led_OBUF[10]} {led_OBUF[11]} {led_OBUF[12]} {led_OBUF[13]} {led_OBUF[14]} {led_OBUF[15]} {led_OBUF[16]} {led_OBUF[17]} {led_OBUF[18]} {led_OBUF[19]} {led_OBUF[20]} {led_OBUF[21]} {led_OBUF[22]} {led_OBUF[23]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list DN_A_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list DN_B_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list DN_C_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list DN_D_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list DN_E_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list DN_F_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list DN_G_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets pll_clk]
